stages:
  - build
  - test

build-job:
  image: "node:lts"
  stage: build
  script:
    - npm ci # Install the npm dependencies
    - npm run build # Build the application

test-job:
  image: "node:lts"
  stage: test
  script:
    - npm ci # Install the npm dependencies
    - npm run test # Test the application